### ISSUE TITLE
Hide the play/pause/stop buttons

### ISSUE THREAD

**Issue by mrdomino** [dwrensha/groovebasin#8]
For my anarchist radio experiment, I'm just passing around capabilities to upload songs and control the stream all over the place.

Consistently what happens is that a user signs on, notices that it's playing music in their browser, doesn't want that, and pushes pause or stop for everyone. It's easy enough to explain how to use "Stream: On" instead, but it'd be even easier if we could just hide the stream control buttons and do an always-on stream.

Maybe this ought to be an upstream issue? If so I'll report it up there too.

**Comment by dwrensha** [comment]
Groove Basin does indeed have separate permissions for listening, controlling the playlist, controlling the audio stream, and uploading tracks. Unfortunately, there are a few things that prevent these from being maximally useful. Sandstorm aggregates permissions into "roles", which are the options presented when a user wants to share a grain. You can currently share the "listener" role, which only allows listening, but if you want to allow uploading you need to share the "contributer" role, which also includes the "controlling the audio stream" permission. (The definitions of the roles and permissions on the Sandstorm side are [here](https://github.com/dwrensha/groovebasin/blob/b33d31ccf438e59ffd92b13940e511fcfed00428/.sandstorm/sandstorm-pkgdef.capnp#L64-L97).) Eventually, we intend to implement an "advanced options" interface, so that you can share with any combination of permissions, rather than being limited to the predefined roles. This would allow you to share the "upload" and "listen" permissions but not the "control" permission. (Arguably, if that's a commonly useful permission combination, we should just define a role for it in the package manifest.)

Another problem is that Groove Basin continues to display the audio stream control buttons even for users who don't have permission to use them. (The buttons don't work, but they are confusing.) I think this is an upstream issue.

**Comment by mrdomino** [comment]
If uploading includes the ability to manage the queue, then yes, I think that role would be useful. I want a class of user that can do anything to the stream except delete stuff from the library or stop the current song. I'd even be okay with them being able to skip the song but I don't have strong feelings either way.

**Comment by dwrensha** [comment]
I've published a new package with a new role "contributor" role that can upload music and create playlists, but cannot control the stream. The old "contributor" role, which could additionally control the stream, has been renamed to "disc jockey".

Unfortunately, Groove Basin currently lumps together the permissions for controlling the currently playing stream and for editing the queue of upcoming songs to-be-played.

**Comment by mrdomino** [comment]
Yay, thanks! I can see that working nicely with like a "queue suggestions" playlist. I think I'll keep anarchy on my stream for now, but when it inevitably breaks down, that's a much cooler state to break down to than just "everyone can only listen unless I trust you."
